### ISSUE TITLE
Minor issue in case a user logs out and then navigates back through the Android navigation

### ISSUE THREAD

**Issue by pezekieva** [HelpAPaw/Android#68]
### Description
I noticed a minor issue in case the user is logged in > logs out and then navigates back using the 'back' button/gesture on Android.

**Steps to reproduce**
1. Log in as a registered user in the application
2. Tap on the side main menu and click on 'Log Out' -> The user is redirected to the Login page
3. Using the Android navigation, click on Back

**Expected result**
The user is navigated back to the application as an anonymous user. In the side menu, under the logo of the app, the user can see the 'Help a Paw' title.

**Actual result**
The user is still seeing their name. 

**Test Data**
user - Polina Ezekieva (p_ezekieva@yahoo.com)
version - 5.1.0(82)
device - Android 11, OxygenOS 11.1.2.2 for OnePlus 6

![image](https://user-images.githubusercontent.com/9154824/154157865-2466334e-99b3-461e-80e2-0a1038b5aecf.png)

**Comment by medeaohm** [comment]
Tова звучи като бъгче и може би е добре наистина да го оправим...

**Comment by medeaohm** [comment]
This is fixed, although now the behaviour is a bit different:
1. Log in as a registered user in the application
2. Tap on the side main menu and click on 'Profile' -> Logout
3. The used is logged out and he no longer sees his name
