### ISSUE TITLE
Update Signal's Title > The change is not reflected in My Notifications

### ISSUE THREAD

**Issue by pezekieva** [HelpAPaw/Android#71]
### Description
Updates of a signal's title are not reflected in 'My Notifications' menu.

**Steps to reproduce**
1. Log in as user1
2. Submit a new signal
3. After the signal is submitted, open it > Tap on Edit > Update the Title of the signal and Save the changes
4. Take another mobile device 
5. Log in with user2 (the signal from the previous steps is within the configured range of this user)
6. Go to the side menu > My Notifications

**Expected result**
The Title of the signal is up to date - the user is able to see the latest updated title.

**Actual result**
The user sees the original title of the signal.

**Note**
The Title is correctly updated in My Signals - both Submitted and Commented.

**Test data**
user1 - psashova@gmail.com
the signal with updated title - https://helpapaw.app.link/Qv5GYvFeJnb
user2 - pezekieva@gmail.com
version - 5.1.0 (83)
device - Android 11, OxygenOS 11.1.2.2 for OnePlus 6

Updated Title:
![image](https://user-images.githubusercontent.com/9154824/154556687-bcec39fa-8976-48ac-8cbd-0786cf3604be.png)

My Notifications view:
![image](https://user-images.githubusercontent.com/9154824/154556886-27aff59c-3ad1-4844-9f3c-f608476c82df.png)

**Comment by medeaohm** [comment]
Tук както за изтритите сигнали - реално ние записваме notification-a локално на конкретният device. Тоест при update/delete на сигнал, това по никакъв начин не се отразава на notification-a.
