### ISSUE TITLE
My Signals and My Notifications > User is seeing deleted signals

### ISSUE THREAD

**Issue by pezekieva** [HelpAPaw/Android#72]
### Description
Deleted Signals are still visible in 'My Signals' and in 'My Notifications'.

**Steps to reproduce**
1. Open the app and log in 
2. Submit a signal in the application
3. Go to side menu > 'My Signals' > 'Submitted Signals'
4. Open the signal created in step 2
5. Go to the signal > Click on Delete (bin) button and delete the Signal
6. Go back to 'My Signals' page

**Expected result**
The deleted signal is no longer visible in the menu.

**Actual result**
The user still sees the signal.

**Note**
The same is reproducible in 'My Signals' > 'Commented Signals'.
Also in 'My Notifications'.

**Test data**
user - p_ezekieva@yahoo.com
deleted signal submitted by this user - https://helpapaw.app.link/kn4KZaYjJnb
deleted signal commented by this user - https://helpapaw.app.link/0KB1uo3jJnb
deleted signal that is still visible in 'My Notifications' - https://helpapaw.app.link/PhKxxZ84Jnb
version - 5.1.0 (83)
device - Android 11, OxygenOS 11.1.2.2 for OnePlus 6

Deleted ones My Signals
![image](https://user-images.githubusercontent.com/9154824/154567582-45add2fe-ea0e-4dec-96ba-f9857569eb2d.png)
![image](https://user-images.githubusercontent.com/9154824/154567712-9f45f77e-4e21-445c-93c9-ec48cb931f34.png)

Deleted ones in My Notifications
![image](https://user-images.githubusercontent.com/9154824/154639293-bdca7267-5f02-4227-84d0-6feb3c5c1ddb.png)

**Comment by BurningAXE** [comment]
@medeaohm Това помня, че го обсъждахме и май умишлено го направихме така!?

**Comment by medeaohm** [comment]
Да, за това поведение има 2 причини:
1. Това е начин user-a да може да намери някой сигнал дори и да е изтрит 
2. Реално ние записваме notification-a локално на конкретният device. Тоест при update/delete на сигнал, това по никакъв начин не се отразава на notification-a.
