### ISSUE TITLE
A signal can be sent only with text, without a phone and photo.

### ISSUE THREAD

**Issue by disvetoslavova** [HelpAPaw/Android#80]
1-Open app "Help a paw".
2-Log in with correct username and password.
3-Tap to the yellow icon with a paw on the right of the page
4-Don't write a phone number and don't attach a photo,write only a text in first feld "Куче без дом"
5-Tap on "Изпрати".
6-Signal is successfully created.

**Comment by BurningAXE** [comment]
Phone and photo are optional.
